""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""" Configuration for initialization
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" let s:init_temporary_directory = user_directory . "/tmp"
" set runtime+=user_directory . "/userautoload"
" runtime! userautoload/*.vim
