- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - caskroom/cask
      - c-bata/kube-prompt

    homebrew_cask_packages:
      - name: google-japanese-ime
      - name: appcleaner
      - name: emacs
      - name: slack
      - name: docker
      - name: google-chrome
      - name: alfred
      - name: spectacle
      - name: bettertouchtool
      - name: 1password
      - name: goland
      - name: webstorm
      - name: iterm2
      - name: google-cloud-sdk
      - name: bettersnaptool

    homebrew_packages:
      - name: git
      - name: tmux
      - name: reattach-to-user-namespace
      - name: fish
      - name: bash # Install bash 4
      - name: bash-completion
      - name: kubernetes-helm
      - name: kubectx
      - name: kube-prompt
      - name: go
      - name: grpc
      - name: terraform
      - name: fzf
      - name: ghq
      - name: mas

  # Install bettersnaptool by mas

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask:
        name: '{{ item.name }}'
        state: installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
      ignore_errors: yes # highly likely this is because applications are already installed
#      register: result
#      ignore_errors: "result.msg.find('It seems there is already an App at') != -1"

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        install_options: '{{ item.install_options | default("") }}'
      with_items: '{{ homebrew_packages }}'
