- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - caskroom/cask

    homebrew_cask_packages:
      - name: appcleaner
      - name: emacs
      - name: slack

    homebrew_packages:
      - name: tmux
      - name: reattach-to-user-namespace
      - name: httpie

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
