- tags:
    - ubuntu-desktop
  block:
    # https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html
    - community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        # Support Emacs shortcut keys in some applications
        # https://discourse.gnome.org/t/gtk-key-themes-for-gnome-shell/3472
        - key: "/org/gnome/desktop/interface/gtk-key-theme"
          value: "'Emacs'"
        # Show a battery percentage on a desktop icon on a laptop
        - key: "/org/gnome/desktop/interface/show-battery-percentage"
          value: true
        # Enable a night light: https://unix.stackexchange.com/a/400036
        - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
          value: true
        # Enable natural-scrolling on a touchpad, especially to show activities
        - key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
          value: true

        # Enable to update a timezone automatically based on a location
        # There is a bug so these configs don't work: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/issues/58
        - key: "/org/gnome/system/location/enabled"
          value: true
        - key: "/org/gnome/desktop/datetime/automatic-timezone"
          value: true

    - tags:
        - always
      include_role:
        name: "{{ role.name }}"
        tasks_from: "{{ role.task | default('main') }}"
      loop:
        - name: vscode
          task: ubuntu
        - name: git
        - name: keyd
      loop_control:
        loop_var: role

    - community.general.snap:
        name: "{{ optional_packages | selectattr('installed', 'equalto', true) | map(attribute='name') | list }}"
        classic: true
      vars:
        # Install guide: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
        optional_packages:
          - name: aws-cli
            installed: "{{ install_aws_cli }}"
          - name: kubectl
            installed: "{{ install_kubectl }}"
          - name: helm
            installed: "{{ install_kubectl }}"
      tags:
        - snap

    - name: Install application packages on Ubuntu
      become: yes
      apt:
        name:
          # - scrcpy # https://github.com/Genymobile/scrcpy
          - xsel # For tmux: https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later

          # gnome console is the default terminal for Gnome: https://release.gnome.org/42/
          # It supports to switch a theme based on a system configuration
          # Also, use the gnome console from the Files app https://fostips.com/gnome-console-default-terminal-ubuntu-2204/
          - gnome-console
          - nautilus-extension-gnome-console
          - nautilus-extension-gnome-terminal

          # Gnome shell extensions: https://itsfoss.com/gnome-shell-extensions/
          # todo: Install a night theme switcher: https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension
          - gnome-shell-extensions
        state: latest
