- tags:
    - ubuntu-desktop
  block:
    - become: true
      apt:
        name:
          - python3-psutil

    - tags:
        - always
      include_role:
        name: "{{ role.name }}"
        tasks_from: "{{ role.task | default('main') }}"
      loop:
        - name: git
        - name: keyd
      loop_control:
        loop_var: role

    - community.general.snap:
        name: "{{ optional_packages | selectattr('installed', 'equalto', true) | map(attribute='name') | list }}"
        classic: true
      become: true
      vars:
        # Install guide: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
        optional_packages:
          - name: aws-cli
            installed: "{{ install_aws_cli }}"
          - name: kubectl
            installed: "{{ install_kubectl }}"
          - name: helm
            installed: "{{ install_kubectl }}"
      tags:
        - snap

    - name: Install application packages on Ubuntu
      become: yes
      apt:
        name:
          # - scrcpy # https://github.com/Genymobile/scrcpy
          - xsel # For tmux: https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later

          # gnome console is the default terminal for Gnome: https://release.gnome.org/42/
          # It supports to switch a theme based on a system configuration
          # Also, use the gnome console from the Files app https://fostips.com/gnome-console-default-terminal-ubuntu-2204/
          - gnome-console
          - nautilus-extension-gnome-console
          - nautilus-extension-gnome-terminal

          # Gnome shell extensions: https://itsfoss.com/gnome-shell-extensions/
          # todo: Install a night theme switcher: https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension
          - gnome-shell-extensions
        state: latest
