- tags:
    - apt
  block:
    - include_role:
        name: apt-repository.1password-cli
    - include_role:
        name: apt-repository.github-cli

    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: yes
      block:
      - name: Update apt cache
        apt:
          update_cache: yes
        ignore_errors: true
      - name: Install application packages on Ubuntu
        apt:
          name:
            - unzip
            - git
            - git-lfs
            - curl
            - fish
            - fzf
            - tmux
            - jq

            - 1password-cli
            - gh
            - mycli
            # Install golang-go by golang role
            # - golang-go
          state: latest
    - name: Check if running on WSL
      shell: "grep -q 'WSL' /proc/version && echo 'true' || echo 'false'"
      register: wsl_check
    - name: WSL Ubuntu
      when: wsl_check.stdout == 'true'
      block:
        - become: yes
          apt:
            name:
              - wslu
            state: latest
    - name: non WSL Ubuntu
      when: wsl_check.stdout == 'false'
      block:
        # TODOs this shouldn't be under apt role
        # - name: Install Microk8s
        #   become: yes
        #   community.general.snap:
        #     name: microk8s
        #     classic: true
        #     channel: 1.26/stable
        - name: Install application packages on Ubuntu
          become: yes
          apt:
            name:
              - scrcpy # https://github.com/Genymobile/scrcpy
              - xsel # For tmux: https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later
            state: latest
