- name: Create symbolic links
  tags:
    - fish
    - tmux
  block:
  - name: Ensure there are a few directories under a home directory
    file:
      path: "{{ ansible_env.HOME }}/{{ item }}"
      state: directory
      mode: "0750"
    loop:
      - .config
      - bin

- import_role:
    name: fish

- tags:
    - ssh
  block:
    - name: Ensure there is the $HOME/.ssh directory
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.ssh"
        mode: 0700
    - name: Copy SSH config
      template:
        src: ssh.config.j2
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: 0600

- template:
    src: .editorconfig.j2
    dest: "{{ ansible_env.HOME }}/.editorconfig"
    mode: 0600
  tags:
    - editorconfig

- template:
    src: .eslintrc.json.j2
    dest: "{{ ansible_env.HOME }}/.eslintrc.json"
    mode: 0600
  tags:
    - eslint

- tags:
    - always
  include_role:
    name: "{{ role }}"
  when: role != ''
  loop:
    - golang
    - "{{ 'gcloud' if install_gcloud_cli else '' }}"
    - "{{ 'kubectl' if install_kubectl else '' }}"
  loop_control:
    loop_var: role
