- tags:
    - always
  include_vars:
    file: ubuntu.yml

- tags:
    - apt
  block:
    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: true
      block:
        - name: Update apt cache
          apt:
            update_cache: true
          ignore_errors: true
        - name: Install application packages on Ubuntu
          apt:
            name: "{{ apt_packages }}"
            state: latest

        - name: Install an app launcher
          block:
            # universe repository cannot be installed by apt_repository, so install it by hand
            # https://github.com/ansible/ansible/issues/48714
            - command: add-apt-repository -y universe
            - apt_repository:
                repo: "{{ item }}"
                state: present
              loop:
                - "ppa:agornostal/ulauncher"
            - apt:
                name:
                  - ulauncher
                state: latest
              # Bookmark launcher cannot be installed by a command
              # Extension install: https://github.com/Ulauncher/Ulauncher/issues/1018
              # Bookmark launcher: https://ext.ulauncher.io/-/github-man0xff-ulauncher-bookmarks
        - apt:
            name:
              # Clipboard manager: https://hluk.github.io/CopyQ/
              - copyq
              # I forgot why I installed this but this is a dependency for something
              - python3-psutil
            state: latest

- tags:
    - always
  include_tasks: all_os.yml

- tags:
    - snap
    - vscode
  become: true
  community.general.snap:
    name: "{{ optional_packages | selectattr('installed', 'equalto', true) | map(attribute='name') | list }}"
    classic: true
  vars:
    # Install guide: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    optional_packages:
      - name: aws-cli
        installed: "{{ install_aws_cli }}"
      - name: kubectl
        installed: "{{ install_kubectl }}"
      - name: helm
        installed: "{{ install_kubectl }}"
      - name: code
        installed: true

- tags:
    - vscode
  include_role:
    name: vscode.config
  vars:
    config_directory: "{{ ansible_env.HOME }}/.config/Code/User"
    meta_key: alt

- import_role:
    name: aws-cli.config
  vars:
    aws_completer_path: /snap/aws-cli/current/bin

- tags:
    - always
  include_role:
    name: "{{ role.name }}"
    tasks_from: "{{ role.task | default('main') }}"
  loop:
    - name: 1password
      task: apt
    - name: git
    - name: github-cli
      task: apt
    - name: keyd
  loop_control:
    loop_var: role

- tags:
    - ubuntu-desktop
  block:
    - name: Install application packages on Ubuntu
      become: true
      apt:
        name:
          # - scrcpy # https://github.com/Genymobile/scrcpy
          - xsel # For tmux: https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later

          # gnome console is the default terminal for Gnome: https://release.gnome.org/42/
          # It supports to switch a theme based on a system configuration
          # Also, use the gnome console from the Files app https://fostips.com/gnome-console-default-terminal-ubuntu-2204/
          - gnome-console
          - nautilus-extension-gnome-console
          - nautilus-extension-gnome-terminal

          # Gnome shell extensions: https://itsfoss.com/gnome-shell-extensions/
          # todo: Install a night theme switcher: https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension
          - gnome-shell-extensions
        state: latest
