- tags:
    - always
  include_vars:
    file: ubuntu.yml

- tags:
    - apt
  block:
    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: true
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
          ignore_errors: true
        - name: Install application packages on Ubuntu
          apt:
            name: "{{ apt_packages }}"
            state: latest

        - name: WSL only packages
          become: true
          apt:
            name:
              - wslu
            state: latest

- tags:
    - always
  include_tasks: all_os.yml

- tags:
    - always
  include_role:
    name: "{{ role }}"
    tasks_from: apt
  loop:
    - 1password
    - github-cli
  loop_control:
    loop_var: role

- import_role:
    name: vscode-config
  vars:
    # The Linux default config directory nor the SSL remote config doesn't work in the WSL
    # config_directory: "{{ ansible_env.HOME }}/.config/Code/User"
    # config_directory: "{{ ansible_env.HOME }}/.vscode-server/data/Machine"
    config_directory: "/mnt/c/Users/{{ host_user }}/AppData/Roaming/Code/User"
    meta_key: alt
    additional_extensions:
      # WSL
      - ms-vscode-remote.remote-containers
      - ms-vscode-remote.remote-wsl

- tags: always
  include_role:
    name: "{{ role.name }}"
    tasks_from: "{{ role.task | default('main') }}"
  loop:
    - name: git
      task: wsl
  loop_control:
    loop_var: role
