- tags:
    - always
  block:
    - name: Get a deb architecture
      shell: dpkg --print-architecture
      register: dpkg_print_architecture_result
    - set_fact:
        deb_architecture: "{{ dpkg_print_architecture_result.stdout }}"

    - name: Check if running on WSL
      shell: "grep -q 'WSL' /proc/version && echo 'true' || echo 'false'"
      register: wsl_check
    - name: WSL Ubuntu
      set_fact:
        is_wsl: "{{ wsl_check.stdout == 'true' }}"

- tags:
    - apt
  block:
    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: yes
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
          ignore_errors: true
        - name: Install application packages on Ubuntu
          apt:
            name:
              - unzip
              - git
              - git-lfs
              - curl
              - fish
              # fzf version is too old from apt until next issue is resolved
              # https://github.com/junegunn/fzf/issues/2599
              # - fzf
              - tmux
              - jq

              - mycli
              # rbenv install ruby where version >= 3 requires libyaml-dev
              - libyaml-dev

            state: latest

    - name: Non WSL
      when: not is_wsl
      block:
        - name: Install an app launcher
          block:
            # universe repository cannot be installed by apt_repository, so install it by hand
            # https://github.com/ansible/ansible/issues/48714
            - become: true
              command: add-apt-repository -y universe
            - become: true
              apt_repository:
                repo: "{{ item }}"
                state: present
              loop:
                - "ppa:agornostal/ulauncher"
            - become: true
              apt:
                name:
                  - ulauncher
                state: latest
              # Bookmark launcher cannot be installed by a command
              # Extension install: https://github.com/Ulauncher/Ulauncher/issues/1018
              # Bookmark launcher: https://ext.ulauncher.io/-/github-man0xff-ulauncher-bookmarks
        - become: true
          apt:
            name:
              # Clipboard manager: https://hluk.github.io/CopyQ/
              - copyq
            state: latest

    - name: WSL Ubuntu
      when: is_wsl
      block:
        - become: yes
          apt:
            name:
              - wslu
            state: latest

- tags:
    - always
  include_tasks: all_os.yml

- tags:
    - always
  include_role:
    name: "{{ role }}"
    tasks_from: apt
  loop:
    - 1password
    - github-cli
  loop_control:
    loop_var: role

- when: not is_wsl
  tags:
    - always
  include_role:
    name: ubuntu-desktop

- when: is_wsl
  tags: always
  include_role:
    name: "{{ role.name }}"
    tasks_from: "{{ role.task | default('main') }}"
  loop:
    - name: vscode
    - name: git
      task: wsl
  loop_control:
    loop_var: role
