- tags:
    - always
  block:
    - name: Get a deb architecture
      shell: dpkg --print-architecture
      register: dpkg_print_architecture_result
    - set_fact:
        deb_architecture: "{{ dpkg_print_architecture_result.stdout }}"

    - name: Check if running on WSL
      shell: "grep -q 'WSL' /proc/version && echo 'true' || echo 'false'"
      register: wsl_check
    - name: WSL Ubuntu
      set_fact:
        is_wsl: wsl_check.stdout == 'true'

- tags:
    - apt
  block:
    - include_role:
        name: apt-repository.1password-cli

    - name: Add a key to an apt_repository
      become: yes
      block:
        - name: Create /etc/apt/keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'
        - name: Download GitHub CLI archive keyring
          get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
            mode: '0644'
        - name: Get DEB architecture
          shell: dpkg --print-architecture
          register: dpkg_print_architecture_result
        - name: Add GitHub CLI repository to sources.list.d
          lineinfile:
            path: /etc/apt/sources.list.d/github-cli.list
            line: "deb [arch={{ dpkg_print_architecture_result.stdout }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
            create: yes


    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: yes
      block:
      - name: Update apt cache
        apt:
          update_cache: yes
        ignore_errors: true
      - name: Install application packages on Ubuntu
        apt:
          name:
            - unzip
            - git
            - git-lfs
            - curl
            - fish
            - fzf
            - tmux
            - jq

            - 1password-cli
            - gh
            - mycli
            # Install golang-go by golang role
            # - golang-go
          state: latest

    - name: WSL Ubuntu
      when: is_wsl
      block:
        - become: yes
          apt:
            name:
              - wslu
            state: latest

    - name: non WSL Ubuntu
      when: not is_wsl
      block:
        # TODOs this shouldn't be under apt role
        # - name: Install Microk8s
        #   become: yes
        #   community.general.snap:
        #     name: microk8s
        #     classic: true
        #     channel: 1.26/stable
        - name: Install application packages on Ubuntu
          become: yes
          apt:
            name:
              - scrcpy # https://github.com/Genymobile/scrcpy
              - xsel # For tmux: https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later
            state: latest

- tags:
    - always
  include_tasks: all_os.yml

- tags:
    - always
  include_role:
    name: "{{ role }}"
    tasks_from: apt
  loop:
    - 1password
  loop_control:
    loop_var: role
