- tags:
    - always
  include_vars:
    file: ubuntu.yml

- tags:
    - apt
  block:
    # Install for Ubuntu, regardless of WSL or non WSL
    - name: Install apt packages
      become: yes
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
          ignore_errors: true
        - name: Install application packages on Ubuntu
          apt:
            name: "{{ apt_packages }}"
            state: latest

        - name: Install an app launcher
          block:
            # universe repository cannot be installed by apt_repository, so install it by hand
            # https://github.com/ansible/ansible/issues/48714
            - become: true
              command: add-apt-repository -y universe
            - become: true
              apt_repository:
                repo: "{{ item }}"
                state: present
              loop:
                - "ppa:agornostal/ulauncher"
            - become: true
              apt:
                name:
                  - ulauncher
                state: latest
              # Bookmark launcher cannot be installed by a command
              # Extension install: https://github.com/Ulauncher/Ulauncher/issues/1018
              # Bookmark launcher: https://ext.ulauncher.io/-/github-man0xff-ulauncher-bookmarks
        - become: true
          apt:
            name:
              # Clipboard manager: https://hluk.github.io/CopyQ/
              - copyq
            state: latest

- tags:
    - always
  include_tasks: all_os.yml

- tags:
    - always
  include_role:
    name: "{{ role }}"
    tasks_from: apt
  loop:
    - 1password
    - github-cli
  loop_control:
    loop_var: role

- tags:
    - always
  include_role:
    name: ubuntu-desktop
