# Vars
## config_directory: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations## host_user: Required. The user name of a Windows host
## host_user: Required on WSL. The user name of a Windows host

- tags:
    - vscode
  block:
    - when:
        - ansible_distribution == 'Ubuntu'
        - ubuntu_type == 'desktop'
      import_tasks: ubuntu_desktop.yml
    - when:
        - ansible_distribution == 'Ubuntu'
        - ubuntu_type == 'wsl'
      import_tasks: wsl_ubuntu.yml
    - when:
        - ansible_distribution == 'MacOSX'
      import_tasks: mac_os.yml
