- tags:
    - vscode
  block:
    - become: true
      snap:
        name: code
        classic: true

    - import_tasks: main.yml
      vars:
        config_directory: "{{ ansible_env.HOME }}/.config/Code/User"
        meta_key: alt
