# Vars:
## host_user: Required. The user name of a Windows host
- import_tasks: main.yml
  vars:
    # The Linux default config directory nor the SSL remote config doesn't work in the WSL
    # config_directory: "{{ ansible_env.HOME }}/.config/Code/User"
    # config_directory: "{{ ansible_env.HOME }}/.vscode-server/data/Machine"
    config_directory: "/mnt/c/Users/{{ host_user }}/AppData/Roaming/Code/User"
    meta_key: alt
    additional_extensions:
      # WSL
      - ms-vscode-remote.remote-containers
      - ms-vscode-remote.remote-wsl
  tags:
    - vscode
