# Vars
## config_directory: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations
- tags:
    - vscode-config
  block:
    - file:
        path: "{{ config_directory }}"
        state: directory
        mode: 0750

    # Copy config files
    # https://bobbyhadz.com/blog/what-is-vscode-folder
    - template:
        src: "{{ item }}"
        dest: "{{ config_directory }}/{{ item | regex_replace('\\.j2$', '') }}"
        mode: 0640
      loop:
        - keybindings.json.j2
        - settings.json.j2

    - command: code --install-extension {{ item }}
      loop:
        # VSCode config
        ## Keybindings: Awesome Emacs Keymap
        - tuttieee.emacs-mcx
        - editorconfig.editorconfig

        ## Themes
        - github.github-vscode-theme
        ### Switch to a night theme automatically
        - muuvmuuv.vscode-sundial
        - johnpapa.vscode-peacock

        ## Spell checker
        - streetsidesoftware.code-spell-checker

        # Copilot
        - github.copilot

        # Git
        # magit: Emacs's magit for VSCode
        # gitlens: For file blame
        - kahole.magit
        - eamodio.gitlens
        - github.vscode-pull-request-github

        # Makefile
        - ms-vscode.makefile-tools

        # Markdown
        - shd101wyy.markdown-preview-enhanced
        - yzhang.markdown-all-in-one
        - marp-team.marp-vscode
        - bierner.markdown-mermaid

        # CSV
        - mechatroner.rainbow-csv
        - randomfractalsinc.tabular-data-viewer

        # JSON
        - esbenp.prettier-vscode

        # Yaml
        - redhat.vscode-yaml

        # Toml
        - tamasfe.even-better-toml

        # Go
        - golang.go

        # TypeScript
        - ms-vscode.vscode-typescript-next
        - esbenp.prettier-vscode
        ## React Native
        - msjsdiag.vscode-react-native

        # Python
        - ms-python.python

        # PHP
        - devsense.composer-php-vscode
        - xdebug.php-debug

        # Fish shell
        - bmalehorn.vscode-fish

        # Protocol buffers
        - zxh404.vscode-proto3

        # Terraform
        - hashicorp.terraform

        # Docker
        - ms-azuretools.vscode-docker

        # Kubernetes
        - ms-kubernetes-tools.vscode-kubernetes-tools
        - ipedrazas.kubernetes-snippets

        # Ansible
        - redhat.ansible
        - wholroyd.jinja

        # SSH
        - ms-vscode-remote.remote-ssh
        - ms-vscode-remote.remote-ssh-edit
