# https://developer.1password.com/docs/cli/get-started
# Require become = yes
- name: Add a apt_repository
  block:
    - name: Download 1Password ASC key
      get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /tmp/1password.asc
    - name: Pack the asc key by GPG
      become: yes
      shell: "cat /tmp/1password.asc | gpg --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg"
    # In a WSL architecture, dpkg --print-architecture is amd64 but ansible_architecture is x86_64
    - name: Get a deb architecture
      shell: dpkg --print-architecture
      register: deb_architecture
    - name: Add 1Password repository to sources list
      apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ deb_architecture.stdout }} stable main"
        state: present
- name: Add the debsig-verify policy
  block:
    - name: Ensure /etc/debsig/policies/AC2D62742012EA22 directory exists
      file:
        path: "/etc/debsig/policies/AC2D62742012EA22"
        state: directory
    - name: Add 1Password debsig policy
      get_url:
        url: https://downloads.1password.com/linux/debian/debsig/1password.pol
        dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    - name: Download 1Password GPG key
      get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /tmp/1password.asc
    - name: Ensure /usr/share/debsig/keyrings/AC2D62742012EA22 directory exists
      file:
        path: /usr/share/debsig/keyrings/AC2D62742012EA22
        state: directory
    - name: Pack the asc key
      become: yes
      shell: "cat /tmp/1password.asc | gpg --yes --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg"
- name: Install 1Password CLI
  become: yes
  apt:
    name: 1password-cli
    state: present
    update_cache: yes
