# https://docs.ansible.com/ansible/2.7/user_guide/playbooks_best_practices.html#operating-system-and-distribution-variance
- tags:
    - always
  block:
    - tags:
        - vscode
      block:
        - become: true
          snap:
            name: code
            classic: true
        - include_role:
            name: vscode.config
          vars:
            config_directory: "{{ ansible_env.HOME }}/.config/Code/User"
            meta_key: alt
