- tags:
    - rancher-desktop
  block:
    - template:
        src: conf-rancher-desktop.fish
        dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/rancher-desktop.fish"
        mode: "0640"
      tags:
        - fish
        - fish.config
