# https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
- name: Add a key to an apt_repository
  become: yes
  block:
    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download GitHub CLI archive keyring
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'
    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: dpkg_print_architecture_result
    - name: Add GitHub CLI repository to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/github-cli.list
        line: "deb [arch={{ dpkg_print_architecture_result.stdout }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        create: yes
