apt_packages:
  # Fix add-apt-repository command not found error: https://phoenixnap.com/kb/add-apt-repository-command-not-found-ubuntu
  - software-properties-common

  - unzip
  - git
  - git-lfs
  - curl
  - fish
  # fzf version is too old from apt until next issue is resolved
  # https://github.com/junegunn/fzf/issues/2599
  # - fzf
  - tmux
  - jq
  - mycli


  # anyenv dependencies
  # - libz-dev # fix an error "zlib.h" not found during rbenv install 2.7.7
  # rbenv install ruby where version >= 3 requires libyaml-dev
  - libyaml-dev
  # pyenv dependencies listed in https://github.com/pyenv/pyenv/wiki#suggested-build-environment
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - curl
  - git
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
