- tags:
    - git
  block:
    - file:
        path: "{{ config_dir }}"
        state: directory
    - set_fact:
        github_org: org
      when: github_org is not defined

    - template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0640
      loop:
        - src: global.gitconfig
          dest: "{{ ansible_env.HOME }}/.gitconfig"
        - src: org.gitconfig
          dest: "{{ config_dir }}/{{ github_org }}.gitconfig"
        - src: global.gitignore
          dest: "{{ config_dir }}/gitignore"
