- tags:
    - anyenv
  vars:
    anyenv_root_dir: "{{ ansible_env.HOME }}/.anyenv"
    # Pass a version to install a specific version of ruby
    # anyenv_ruby_version: "3.3.5"
  block:
    - name: Install anyenv
      block:
        - name: Clone anyenv repository
          git:
            repo: "https://github.com/anyenv/anyenv"
            dest: "{{ anyenv_root_dir }}"
        - name: Initialize anyenv
          command:
            cmd: "{{ anyenv_root_dir }}/bin/anyenv install --force-init"
            creates: "{{ ansible_env.HOME }}/.config/anyenv/anyenv-install"
    - name: Install rbenv
      tags:
        - rbenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install rbenv"
        creates: "{{ anyenv_root_dir }}/envs/rbenv"

    # Install a ruby for some tools like tmuxinator
    - name: Install ruby
      tags:
        - ruby
      block:
        - command:
            cmd: "{{ anyenv_root_dir }}/envs/rbenv/bin/rbenv install {{ anyenv_ruby_version }}"
            creates: "{{ anyenv_root_dir }}/envs/rbenv/versions/{{ anyenv_ruby_version }}"
        - command:
            cmd: "{{ anyenv_root_dir }}/envs/rbenv/bin/rbenv global {{ anyenv_ruby_version }}"
            creates: "{{ ansible_env.HOME }}/.rbenv/version"

    - name: Install pyenv
      tags:
        - pyenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install pyenv"
        creates: "{{ anyenv_root_dir }}/envs/pyenv"

    - name: Install nodenv
      tags:
        - nodenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install nodenv"
        creates: "{{ anyenv_root_dir }}/envs/nodenv"

    - name: Install tfenv
      tags:
        - tfenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install tfenv"
        creates: "{{ anyenv_root_dir }}/envs/tfenv"

    - tags:
        - anyenv.config
        - fish.config
      block:
        - template:
            src: anyenv.fish
            dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/anyenv.fish"
            mode: "0644"
