- tags:
    - anyenv
    - pyenv
    - rbenv
  vars:
    anyenv_root_dir: "{{ ansible_env.HOME }}/.anyenv"
  block:
    - name: Install anyenv
      tags:
        - anyenv
      block:
        - name: Clone anyenv repository
          git:
            repo: "https://github.com/anyenv/anyenv"
            dest: "{{ anyenv_root_dir }}"
        - name: Initialize anyenv
          command:
            cmd: "{{ anyenv_root_dir }}/bin/anyenv install --force-init"
            creates: "{{ ansible_env.HOME }}/.config/anyenv/anyenv-install"
    - name: Install rbenv
      tags:
        - anyenv
        - rbenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install rbenv"
        creates: "{{ anyenv_root_dir }}/envs/rbenv"
    - name: Install pyenv
      tags:
        - anyenv
        - pyenv
      command:
        cmd: "{{ anyenv_root_dir }}/bin/anyenv install pyenv"
        creates: "{{ anyenv_root_dir }}/envs/pyenv"

      # todo: This doesn't work for a new installation when `tfenv install latest` runs
      # - name: Install tfenv
      #   tags:
      #     - tfenv
      #   block:
      #   - name: Check if tfenv is already installed
      #     stat:
      #       path: "{{ ansible_env.HOME }}/.anyenv/envs/tfenv"
      #     register: tfenv_directory
      #   - name: Install tfenv
      #     when: not tfenv_directory.stat.exists
      #     block:
      #       - name: Install tfenv
      #         command: "~/.anyenv/bin/anyenv install tfenv"
      #   - command: tfenv install latest
