- tags:
    - github-cli
  block:
    - name: Setup fish completion
      block:
        - name: gh completion for fish shell
          command: gh completion -s fish > ~/.config/fish/completions/gh.fish
