- tags:
    - github-cli
  block:
    - name: Setup fish completion
      block:
        - name: gh completion for fish shell
          command: gh completion -s fish > ~/.config/fish/completions/gh.fish

    - name: Install extensions
      command:
        cmd: gh extension install {{ item }}
      loop:
        - https://github.com/nektos/gh-act

    - template:
        src: PULL_REQUEST_TEMPLATE.md
        dest: ~/.config/gh/PULL_REQUEST_TEMPLATE.md
        mode: 0600
